export type { Client, MatSpec, ClientNote, ClientCategory } from './types'
export { CLIENT_CATEGORIES } from './types'
export type { PaymentInfo, ChurnRiskClientInfo, ChurnRiskLevel, ChurnRiskReason } from './components/ClientsTable'
export { CHURN_REASON_LABELS } from './components/ClientsTable'
export { getClientReplacements, isClientPaused, formatPausedUntil, formatWorkingHours } from './types'
export { useClientStore } from './store'
export { ClientsTable } from './components/ClientsTable'
export { AddClientDialog } from './components/AddClientDialog'
export { EditClientDialog } from './components/EditClientDialog'
export { BatchGeocode } from './components/BatchGeocode'
export { GeocodeSettings } from './components/GeocodeSettings'
export { ServiceHistory } from './components/ServiceHistory'
export { PauseClientDialog } from './components/PauseClientDialog'
export { CostSettingsDialog } from './components/CostSettingsDialog'
export { ClientsPrintView } from './components/ClientsPrintView'
